name: Front CI

on:
  push:
    branches: [main]
    paths:
      - "front/**"
      - "api/**"
  pull_request:
    branches: [main]
    paths:
      - "front/**"
      - "api/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.19
        uses: actions/setup-node@v4
        with:
          node-version: "22.19"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint --workspace=front

      - name: Type checking
        run: npm run typecheck --workspace=front

      # Cuando metáis tests
      # - name: Run tests
      #   run: npm run test --workspace=front
